<<<<<<< HEAD
# Generated by Django 5.1.7 on 2025-03-20 08:53
=======
# Generated by Django 5.1.7 on 2025-03-18 06:48
>>>>>>> 7a19a01763bee7358ae2c331bf58cd4e117576b7

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
<<<<<<< HEAD
=======
                ('full_name', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=10)),
>>>>>>> 7a19a01763bee7358ae2c331bf58cd4e117576b7
            ],
        ),
    ]
